### ISSUE TITLE
Same video over and over again when recovering cameras

### ISSUE THREAD

**Issue by Adrygag95** [Assasans/found-footage#1]
[content_warning_7fffffff.webm](https://github.com/Assasans/found-footage/assets/93791868/16c32bda-ae2c-4d80-be95-bd876ef1fe43)

I'm always getting the same video of one blue player with (º_`) face playing by himself and dying to some machine wheels. All my found footage cameras display that video no matter what. Even between matches and saves. Looks like a test webm for development??

**Comment by Assasans** [comment]
Hello!

There was a bug on the server, so new videos weren't being added to the database, only to the object store. I regenerated the rows, so this is fixed now.
The problem with getting the same video is because I use `video_id < random_uuid` to get random video. This introduces bias when there are few videos. I'll fix this in a future release.

**Comment by Adrygag95** [comment]
Oh thank you so much! Our friends and I had a good laugh tho even with the bug. Very creative mod, thank you for the hard work!
