### ISSUE TITLE
Extract error

### ISSUE THREAD

**Issue by HaSKeR1** [Assasans/found-footage#10]
[LogOutput.log](https://github.com/Assasans/found-footage/files/14970476/LogOutput.log)

**Comment by Assasans** [comment]
The mod cannot access the server due to Cloudflare Workers domain being blocked in Russia and China.
Try opening https://foundfootage-server.assasans.dev/version in a browser, this should work as it is no longer a `*.workers.dev` domain. If so, set `ServerUrl = https://foundfootage-server.assasans.dev` in the mod's config file (`BepInEx/config/jp.assasans.cw.FoundFootage.cfg`).
