### ISSUE TITLE
mod is not working

### ISSUE THREAD

**Issue by koteiyt** [Assasans/found-footage#9]
when I start the game, the mod does not work, and an error appears, I attach logs and a screenshot to the message,a MyceliumNetworking is working
![image](https://github.com/Assasans/found-footage/assets/166993941/80045acf-7f46-4fda-a038-560a9baf0cc9)
[LogOutput.log](https://github.com/Assasans/found-footage/files/14970335/LogOutput.log)

**Comment by koteiyt** [comment]
and when I try to make a video disc from the camera, he writes "failed to extract" and gives me money with views

**Comment by Assasans** [comment]
The mod cannot access the server due to Cloudflare Workers domain possibly being blocked by your ISP.
Try opening https://foundfootage-server.assasans.dev/version in a browser, this should work as it is no longer a `*.workers.dev` domain. If so, set `ServerUrl = https://foundfootage-server.assasans.dev` in the mod's config file (`BepInEx/config/jp.assasans.cw.FoundFootage.cfg`).

**Comment by koteiyt** [comment]
THANKS YOU,i swapped server url and it WORKS!
